import pathlib

from chem_analysis.gc_lc.effective_carbon_number import calculate_effective_carbon_number

data = (
    ('a6', 'CCCCCCO'),
    ('a7', 'CCCCCCCO'),
    ('a8', 'CCCCCCCCO'),
    ('a9', 'CCCCCCCCCO'),
    ('a10_4', 'CCCCCC(O)CCCC'),
    ('a10_5', 'CCCCCCC(O)CCC'),
    ('a10_3', 'CCCCCCCC(O)CC'),
    ('a10_2', 'CCCCCCCCC(O)C'),
    ('a10', 'CCCCCCCCCCO'),
    ('a3', 'CCCO'),
    ('a4', 'CCCCO'),
    ('a5', 'CCCCCO'),
    ('AA5', 'CCCCCOC(=O)C'),
    ('AA6', 'CCCCCCOC(=O)C'),
    ('AA7', 'CCCCCCCOC(=O)C'),
    ('AA8', 'CCCCCCCCOC(=O)C'),
    ('AA10_5', 'CCCCCC(OC(=O)C)CCCC'),
    ('AA10_4', 'CCCCCCC(OC(=O)C)CCC'),
    ('AA10_3', 'CCCCCCCC(OC(=O)C)CC'),
    ('AA9', 'CCCCCCCCCOC(=O)C'),
    ('AA10_2', 'CCCCCCCCC(OC(=O)C)C'),
    ('AA10', 'CCCCCCCCCCOC(=O)C'),
    ('AA3', 'CCCOC(=O)C'),
    ('AA4', 'CCCCOC(=O)C'),
    ('A4', 'CCCCO[Si](C)(C)C'),
    ('A5', 'CCCCCO[Si](C)(C)C'),
    ('A6', 'CCCCCCO[Si](C)(C)C'),
    ('A7', 'CCCCCCCO[Si](C)(C)C'),
    ('A8', 'CCCCCCCCO[Si](C)(C)C'),
    ('A10_5', 'CCCCCC(O[Si](C)(C)C)CCCC'),
    ('A10_4', 'CCCCCCC(O[Si](C)(C)C)CCC'),
    ('A9', 'CCCCCCCCCO[Si](C)(C)C'),
    ('A10_3', 'CCCCCCCC(O[Si](C)(C)C)CC'),
    ('A10_2', 'CCCCCCCCC(O[Si](C)(C)C)C'),
    ('A10', 'CCCCCCCCCCO[Si](C)(C)C'),
    ('A3', 'CCO[Si](C)(C)C'),
    ('TCB', 'ClC1=C(Cl)C=C(Cl)C=C1'),
    ('ca3', 'OC(=O)CC'),
    ('ca4', 'OC(=O)CCC'),
    ('ca5', 'OC(=O)CCCC'),
    ('ca6', 'OC(=O)CCCCC'),
    ('ca7', 'OC(=O)CCCCCC'),
    ('ca8', 'OC(=O)CCCCCCC'),
    ('ca9', 'OC(=O)CCCCCCCC'),
    ('ca10', 'OC(=O)CCCCCCCCC'),
    ('CA3', '[Si](C)(C)(C)OC(=O)CC'),
    ('CA4', '[Si](C)(C)(C)OC(=O)CCC'),
    ('CA5', '[Si](C)(C)(C)OC(=O)CCCC'),
    ('CA6', '[Si](C)(C)(C)OC(=O)CCCCC'),
    ('CA7', '[Si](C)(C)(C)OC(=O)CCCCCC'),
    ('CA8', '[Si](C)(C)(C)OC(=O)CCCCCCC'),
    ('CA9', '[Si](C)(C)(C)OC(=O)CCCCCCCC'),
    ('CA10', '[Si](C)(C)(C)OC(=O)CCCCCCCCC'),
    ('da4', 'OC(=O)CCC(=O)O'),
    ('da5', 'OC(=O)CCCC(=O)O'),
    ('da6', 'OC(=O)CCCCC(=O)O'),
    ('da7', 'OC(=O)CCCCCC(=O)O'),
    ('da8', 'OC(=O)CCCCCCC(=O)O'),
    ('da9', 'OC(=O)CCCCCCCC(=O)O'),
    ('da10', 'OC(=O)CCCCCCCCC(=O)O'),
    ('DA4', '[Si](C)(C)(C)OC(=O)CCC(=O)O[Si](C)(C)(C)'),
    ('DA5', '[Si](C)(C)(C)OC(=O)CCCC(=O)O[Si](C)(C)(C)'),
    ('DA6', '[Si](C)(C)(C)OC(=O)CCCCC(=O)O[Si](C)(C)(C)'),
    ('DA7', '[Si](C)(C)(C)OC(=O)CCCCCC(=O)O[Si](C)(C)(C)'),
    ('DA8', '[Si](C)(C)(C)OC(=O)CCCCCCC(=O)O[Si](C)(C)(C)'),
    ('DA9', '[Si](C)(C)(C)OC(=O)CCCCCCCC(=O)O[Si](C)(C)(C)'),
    ('DA10', '[Si](C)(C)(C)OC(=O)CCCCCCCCC(=O)O[Si](C)(C)(C)'),
    ('ha2', 'OC(=O)CO'),
    ('ha3', 'OC(=O)CCO'),
    ('ha4', 'OC(=O)CCCO'),
    ('ha5', 'OC(=O)CCCCO'),
    ('ha6', 'OC(=O)CCCCCO'),
    ('ha7', 'OC(=O)CCCCCCO'),
    ('ha8', 'OC(=O)CCCCCCCO'),
    ('ha9', 'OC(=O)CCCCCCCCO'),
    ('ha10', 'OC(=O)CCCCCCCCCO'),
    ('HAA2', '[Si](C)(C)(C)OC(=O)COC(=O)O'),
    ('HAA3', '[Si](C)(C)(C)OC(=O)CCOC(=O)O'),
    ('HAA4', '[Si](C)(C)(C)OC(=O)CCCOC(=O)O'),
    ('HAA5', '[Si](C)(C)(C)OC(=O)CCCCOC(=O)O'),
    ('HAA6', '[Si](C)(C)(C)OC(=O)CCCCCOC(=O)O'),
    ('HAA7', '[Si](C)(C)(C)OC(=O)CCCCCCOC(=O)O'),
    ('HAA8', '[Si](C)(C)(C)OC(=O)CCCCCCCOC(=O)O'),
    ('HAA9', '[Si](C)(C)(C)OC(=O)CCCCCCCCOC(=O)O'),
    ('HAA10', '[Si](C)(C)(C)OC(=O)CCCCCCCCCOC(=O)O'),
    ('HA2', '[Si](C)(C)(C)OC(=O)CO[Si](C)(C)(C)'),
    ('HA3', '[Si](C)(C)(C)OC(=O)CCO[Si](C)(C)(C)'),
    ('HA4', '[Si](C)(C)(C)OC(=O)CCCO[Si](C)(C)(C)'),
    ('HA5', '[Si](C)(C)(C)OC(=O)CCCCO[Si](C)(C)(C)'),
    ('HA6', '[Si](C)(C)(C)OC(=O)CCCCCO[Si](C)(C)(C)'),
    ('HA7', '[Si](C)(C)(C)OC(=O)CCCCCCO[Si](C)(C)(C)'),
    ('HA8', '[Si](C)(C)(C)OC(=O)CCCCCCCO[Si](C)(C)(C)'),
    ('HA9', '[Si](C)(C)(C)OC(=O)CCCCCCCCO[Si](C)(C)(C)'),
    ('HA10', '[Si](C)(C)(C)OC(=O)CCCCCCCCCO[Si](C)(C)(C)'),
    ('K6_2', 'CCCCC(=O)C'),
    ('K7_2', 'CCCCCC(=O)C'),
    ('K8_2', 'CCCCCCC(=O)C'),
    ('K9_2', 'CCCCCCCC(=O)C'),
    ('K10_4', 'CCCCCCC(=O)CCC'),
    ('K10_5', 'CCCCCC(=O)CCCC'),
    ('K10_3', 'CCCCCCCC(=O)CC'),
    ('K10_2', 'CCCCCCCCC(=O)C'),
    ('K10', 'CCCCCCCCCC=O'),
    ('EA', 'CC(=O)OC'),
    ('L5', 'O1CCCCC1=O'),
    ('L6', 'O1CCCCCC1=O'),
    ('C10', 'CCCCCCCCCC'),
    ('P10', 'OOCCCCCCCCCC'),
    ('P10_2', 'CC(OO)CCCCCCCC'),
    ('P10_3', 'CCC(OO)CCCCCCC'),
    ('P10_4', 'CCCC(OO)CCCCCC'),
    ('P10_5', 'CCCCC(OO)CCCCC'),
    ('A=10', 'OC=CCCCCCCCC'),
    ('CA=10', 'OC(=O)C=CCCCCCCC'),
    ('AA=10_3', 'C=C(OC(=O)C)CCCCCCCC'),
    ('D10_1_2', 'OCC(O)CCCCCCCC'),
    ('Br10', 'CCCCCCCCCCBr'),
    ('Br10_2', 'CCCCCCCCC(Br)C'),
    ('Br10_3', 'CCCCCCCC(Br)CC'),
    ('Br10_4', 'CCCCCCC(Br)CCC'),
    ('Br10_5', 'CCCCCC(Br)CCCC'),
    ('D2', 'OCCO'),
    ('D3', 'OCCCO'),
    ('D4', 'OCCCCO'),
    ('D5', 'OCCCCCO'),
    ('D6', 'OCCCCCCO'),
    ('D7', 'OCCCCCCCO'),
    ('D8', 'OCCCCCCCCO'),
    ('D9', 'OCCCCCCCCCO'),
    ('D10', 'OCCCCCCCCCCO'),
    ('K6', 'CCCCCC=O'),
    ('K7', 'CCCCCCC=O'),
    ('K8', 'CCCCCCCC=O'),
    ('K9', 'CCCCCCCCC=O'),
    ('L4_4', 'C1CCC(=O)O1'),
    ('L5_4', 'CC1CCC(=O)O1'),
    ('L6_4', 'CCC1CCC(=O)O1'),
    ('L7_4', 'CCCC1CCC(=O)O1'),
    ('L8_4', 'CCCCC1CCC(=O)O1'),
)


def save_csv(filename: pathlib.Path, labels: list[str], rf: list[float]) -> str:
    text = "\n".join(f"{label},{r}" for label, r in zip(labels, rf))

    if filename is not None:
        with open(filename, "w") as f:
            f.write(text)
    return text


def main(data_path: pathlib.Path):
    rf = []
    labels = []
    for label, smile in data:
        rf.append(calculate_effective_carbon_number(smile))
        labels.append(label)

    save_csv(data_path, labels, rf)


if __name__ == '__main__':
    path = pathlib.Path(r"C:\Users\nicep\Desktop\research_wis\data\reference_data\gc_ms\decane\ECN_FID_MC.csv")
    main(path)
